### ISSUE TITLE
does not support whitespace control hyphens

### ISSUE THREAD

**Issue by revelt** [motet-a/jinjalint#11]
consider a file consisting of only:

```jinja
{%- set z = true -%}
```

It is a valid expression in Jinja but currently `jinjalint` will swear about it:

```
index.html:1:2: Parse error: expected one of 'a letter', 'autoescape', 'block', 'blocktrans', 'comment', 'filter', 'for', 'if', 'ifchanged', 'ifequal', 'ifnotequal', 'spaceless', 'verbatim', 'with' at 0:2
```

I wonder if it's an issue or something's wrong with my install of `jinjalint`..

**Comment by motet-a** [comment]
This is an issue with jinjalint, currently I have tested it with Django's flavor of Jinja which doesn't support some Jinja features like this one. However this one is really easy to implement so I'll add support for it soon.

**Comment by revelt** [comment]
thank you, also, let's consider `{{-` at the same go, so both `{%-` and `{{-` would work

**Comment by motet-a** [comment]
@revelt I just published fa60351f59e6eee82f52c3ff1a894f140768e781 in a new version on Pypi so these whitespace control hyphens and pluses should be handled properly.

**Comment by motet-a** [comment]
I’ll close the issue, but please let me know here if anything is going wrong.

**Comment by revelt** [comment]
Good work! I just tried linting, it does pass, there's only a bunch of indentation errors (which I'll find out how to disable) but otherwise healthy files pass fine now. Thank you very much!

**Comment by motet-a** [comment]
I’m glad to hear that :slightly_smiling_face:
