### ISSUE TITLE
Add Support for pre-commit

### ISSUE THREAD

**Issue by anonfriese** [motet-a/jinjalint#13]
It would be great to be able to run this Jinja Linter as part of my pre-commit hooks.

I think the only part needed for that might be a .pre-commit-hooks.yaml-File in this repository (see https://pre-commit.com/#new-hooks ).

Maybe I'll take a stab on this myself and add a Pull Request....

**Comment by motet-a** [comment]
Hi,

I didn’t know https://pre-commit.com/. What do you think of [this `.pre-commit-hooks.yaml` file](https://github.com/motet-a/jinjalint/commit/b8f1043349ba640fb303ef268c3af3267988d21c) I just wrote?

**Comment by anonfriese** [comment]
Hi,

looks great. Only addition I would make:

`language_version: python3
`

Since jinjalint is only compatible with Python 3, it should be explictly specified. My System for example is still running Python 2 by default and so the pre-commit hook failed.

I also would have liked to add a RegEx to match which files the Hook will be run against, but i hit against #9 there :-(

Here's my WIP:
https://github.com/anonfriese/jinjalint/blob/master/.pre-commit-hooks.yaml

**Comment by asottile** [comment]
woops, sorry didn't notice the work already started on this -- I've taken a stab in #14

**Comment by motet-a** [comment]
Oops, looks like I missed your last message @anonfriese… Sorry. Thanks to both of you in anyway.

**Comment by asottile** [comment]
Adding this to our list of hooks as well! https://github.com/pre-commit/pre-commit.github.io/pull/195

**Comment by motet-a** [comment]
@anonfriese BTW #9 is fixed, there’s an `--extension` option now.
